
name: Middleman Github Pages Action
description: 'Deploying your Middleman repo to the gh-pages branch of the same repository'
author: "Zooniverse Team"
branding:
  icon: 'box'
  color: 'teal'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  GIT_USERNAME:
    description: 'Name of that will show in git history'
    required: false
    default: 'zooniverse-ci'
  GIT_EMAIL:
    description: 'Email of the git user'
    required: false
    default: 'ci@zooniverse.org'
  GIT_PUSH_DRY_RUN:
    description: 'Dry run the github push'
    required: false
    default: ''
  SITE_LOCATION:
    description: 'Location of Middleman project within your repo'
    required: false
    default: '.'
  BUILD_LOCATION:
    description: 'Location where Middleman builds your website'
    required: false
    default: 'build'
  REMOTE_BRANCH:
    description: 'Branch name to push built sity to'
    required: false
    default: 'gh-pages'
  GITHUB_TOKEN:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
