
name: Middleman Github Pages Action
description: 'Deploying your Middleman repo to the gh-pages branch of the same repository'
author: "Zooniverse Team"
branding:
  icon: 'box'
  color: 'teal'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  GITHUB_REPOSITORY:
    description: 'Github repository to push built site to'
    required: false
    default: ${{ github.repository }}
  GITHUB_ACTOR:
    description: 'Name of the deploy actor'
    required: false
    default: ${{ github.actor }}
  GIT_PUSH_DRY_RUN:
    description: 'Dry run the github push'
    required: false
    default: ''
  SITE_LOCATION:
    description: 'Location of Middleman project within your repo'
    required: false
    default: '.'
  BUILD_LOCATION:
    description: 'Location where Middleman builds your website'
    required: false
    default: 'build'
  REMOTE_BRANCH:
    description: 'Branch name to push built sity to'
    required: false
    default: 'gh-pages'
  GITHUB_TOKEN:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
